import type { Metadata } from "next";
import { RFQForm } from "@/components/RFQForm";
export const metadata: Metadata = { title: "Contact & Request a Quote", description: "Request a quote from Shivaflex for industrial PVC and braided hose products." };
const offices = [
  ["Head office / Unit 1", "Bikaner Road, N.H.-89, Nokha (Bikaner), Rajasthan, India – 334803", "Tel: +91-1531-220313 · Mobile: +91-9414139280 / +91-7891515751"],
  ["Manufacturing Unit 2", "Lakhibati More, RO-Maillickpur, PS-Margram, West Bengal 731224", ""],
  ["Manufacturing Unit 3", "Kantalia Road, Howrah, West Bengal 711409", ""],
  ["Marketing offices", "Genius Marketing, Jaipur, Rajasthan · Genius Polytex, Kolkata, West Bengal", "Secondary: info.geniuspolytex@gmail.com"],
];
export default function ContactPage() { return <main><section className="border-b border-slate-200 bg-mist py-16"><div className="container-site"><p className="eyebrow">Contact sales</p><h1 className="section-title">Let’s specify the right hose</h1><p className="mt-5 max-w-2xl leading-7 text-slate-600">Tell us your application, dimensions, pressure and quantity. Our team can guide the right product selection.</p></div></section><section id="rfq" className="scroll-mt-24 py-20"><div className="container-site grid gap-12 lg:grid-cols-[.82fr_1.18fr]"><aside><p className="eyebrow">Direct contact</p><h2 className="section-title">Talk to Shivaflex</h2><p className="mt-5 text-sm leading-7 text-slate-600">Contact person: <strong>Mr. Mitesh Maheshwari</strong></p><a href="mailto:info@shivaflex.com" className="mt-5 block text-lg font-bold text-brand hover:text-secondary hover:underline">info@shivaflex.com</a><a href="tel:+911531220313" className="mt-2 block text-lg font-bold text-brand hover:text-secondary hover:underline">+91-1531-220313</a></aside><div className="bg-mist p-7 sm:p-9"><p className="eyebrow">Request for quotation</p><h2 className="mt-2 font-display text-3xl uppercase">Share your requirement</h2><div className="mt-7"><RFQForm /></div><p className="mt-4 text-xs text-slate-500">[TODO: connect form to the approved email/CRM service before launch.]</p></div></div></section><section className="bg-mist py-20"><div className="container-site"><p className="eyebrow">Locations</p><h2 className="section-title">Manufacturing & marketing offices</h2><p className="mt-4 text-sm text-amber-700">Client check: the brochure lists Unit 1’s pin code as 343084; current company records list 334803. Please confirm the correct pin code before launch.</p><div className="mt-9 grid gap-5 md:grid-cols-2">{offices.map(([name, address, contact]) => <article key={name} className="bg-white p-6 shadow-sm"><h3 className="font-display text-2xl uppercase">{name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{address}</p>{contact && <p className="mt-3 text-sm font-semibold text-slate-700">{contact}</p>}<div className="mt-5 grid h-32 place-items-center bg-slate-200 text-center text-xs font-semibold text-slate-500">Map placeholder<br />[TODO: add approved embedded map]</div></article>)}</div></div></section></main>; }
