import Link from "next/link";
import { ApplicationTile } from "@/components/ApplicationTile";
import { ProductCoverflow } from "@/components/ProductCoverflow";
import { ProductImage } from "@/components/ProductImage";
import { Reveal } from "@/components/Reveal";
import { StatCounter } from "@/components/StatCounter";
import { applications, products } from "@/lib/products";

export default function Home() { const featured = products.filter((p) => ["medium-duty-green-hose", "transparent-pneumatic-hose", "delivery-hose-pipe", "flex-duct-hose"].includes(p.slug)); return <main>
  <section className="overflow-hidden border-b border-slate-200 bg-white"><div className="container-site grid min-h-[530px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><Reveal><p className="eyebrow">Shivom Rubber Products (P) Ltd.</p><h1 className="mt-4 max-w-3xl font-display text-5xl uppercase leading-[.95] text-ink sm:text-7xl">Ready to Challenge <span className="text-brand">– Flexibility 'N' Strength</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">Specification-led PVC and braided hose solutions for agriculture, construction, industry and infrastructure.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact#rfq" className="btn-primary">Request a Quote</Link><Link href="/products" className="btn-secondary">Browse Products</Link></div></Reveal><Reveal delay={0.12} className="relative"><div className="relative aspect-[5/4] overflow-hidden border border-slate-200"><ProductImage src="/images/hero/industrial-hose-hero.jpg" alt="Industrial hose coils at Shivaflex" /><div className="absolute bottom-0 left-0 bg-white/95 px-5 py-4 text-sm font-bold text-brand">PVC & braided hose manufacturer · India</div></div></Reveal></div></section>
  <section className="border-b border-slate-200 bg-mist"><div className="container-site grid gap-7 py-8 sm:grid-cols-3"><StatCounter value={25} suffix="+" label="years of hose-making experience" /><StatCounter value={3} label="manufacturing units" /><StatCounter value={17} suffix="+" label="product lines for industrial use" /></div></section>
  <section className="bg-mist py-20"><div className="container-site"><Reveal><p className="eyebrow">Find the right hose faster</p><h2 className="section-title">Shop by application</h2><p className="mt-4 max-w-2xl text-slate-600">Start with what the hose needs to do. We’ll help you match construction, size and pressure to the job.</p></Reveal><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{applications.map((item, index) => <Reveal key={item} delay={index * 0.07}><ApplicationTile name={item} /></Reveal>)}</div></div></section>
  <ProductCoverflow products={featured} />
  <section className="border-y border-slate-200 bg-mist py-20"><div className="container-site grid items-center gap-10 lg:grid-cols-2"><Reveal><p className="eyebrow">Manufacturing & quality</p><h2 className="section-title">Capability you can specify with confidence</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">A fully automatic plant, extrusion and braiding capability, compounding and in-house tensile and pressure testing support consistent supply for domestic markets.</p><Link href="/about-quality" className="btn-secondary mt-7">About our quality process</Link></Reveal><Reveal delay={.1} className="relative"><div className="relative aspect-video overflow-hidden border border-slate-200"><ProductImage src="/images/manufacturing/plant-floor.jpg" alt="Shivaflex manufacturing plant floor" /></div></Reveal></div></section>
  <section className="bg-[#E7F1F7] py-16"><div className="container-site flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><p className="eyebrow">Dealers & distributors</p><h2 className="section-title">Grow your hose portfolio with Shivaflex</h2><p className="mt-3 text-slate-600">Reliable bulk supply for regional dealers, distributors and traders.</p></div><Link href="/dealers" className="btn-primary shrink-0">Become a partner</Link></div></section>
</main>; }
