export type Product = {
  slug: string;
  name: string;
  family: "Suction Hose" | "Braided Hose" | "Delivery Hose" | "Specialty Hose";
  applications: string[];
  image: string;
  short: string;
  features: string[];
  sizes: string;
  workingPressure: string;
  burstingPressure: string;
  exactSpecs?: boolean;
};

// This is the master product and photography-shot list. Add confirmed specifications here.
export const products: Product[] = [
  { slug: "medium-duty-green-hose", name: "Medium Duty (Green) Suction Hose", family: "Suction Hose", applications: ["Agriculture & Irrigation", "Water Transfer", "Light Industrial"], image: "/images/products/medium-duty-green-hose.jpg", short: "Flexible green PVC suction hose for irrigation and general water transfer.", features: ["Lightweight and flexible", "Designed to resist kinking and bursting", "High vacuum and pressure resistance", "Suitable for saline water and light acids/alkalis; not for solvents"], sizes: "20 mm–200 mm I.D.", workingPressure: "3.5–7 kg/cm²", burstingPressure: "8–24 kg/cm²", exactSpecs: true },
  { slug: "heavy-duty-hose", name: "Heavy Duty Suction Hose", family: "Suction Hose", applications: ["Mining & Quarry", "Construction", "Abrasive Material Handling", "Fire & Safety"], image: "/images/products/heavy-duty-hose.jpg", short: "Abrasion-resistant suction and delivery hose for demanding material handling.", features: ["High external-impact resistance", "Resists kinking, bulging and bursting", "For serious suction and delivery conditions", "Suitable for abrasive materials"], sizes: "20 mm–200 mm I.D.", workingPressure: "2.5–5 kg/cm²", burstingPressure: "6–25 kg/cm²", exactSpecs: true },
  { slug: "flex-duct-hose", name: "Flex Duct Hose", family: "Suction Hose", applications: ["HVAC & Fume Removal", "Dust Handling", "Agriculture & Irrigation"], image: "/images/products/flex-duct-hose.jpg", short: "Very light, flexible reinforced duct hose for air, gas and light solids conveyance.", features: ["Very lightweight and easy to handle", "Rigid outer reinforcement", "For air, gases, fumes and dust", "Also available with heavy square-corrugated outer surface"], sizes: "20 mm–200 mm I.D.", workingPressure: "[TODO: confirm with client]", burstingPressure: "[TODO: confirm with client]", exactSpecs: true },
  { slug: "transparent-pneumatic-hose", name: "Transparent & Pneumatic Air Hose", family: "Braided Hose", applications: ["Pneumatic & Air", "Industrial", "Automotive/Car Wash"], image: "/images/products/transparent-pneumatic-hose.jpg", short: "Clear flexible hose for pneumatic lines and general industrial air transfer.", features: ["Transparent construction for visual flow checks", "Flexible routing", "For pneumatic and general utility use"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "water-hose", name: "Water Hose", family: "Braided Hose", applications: ["Water Transfer", "Construction", "Agriculture & Irrigation"], image: "/images/products/water-hose.jpg", short: "General-purpose braided water hose for controlled water delivery.", features: ["Flexible braided construction", "For routine water supply and transfer", "Available in application-specific configurations"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "garden-hose", name: "Garden Hose", family: "Braided Hose", applications: ["Agriculture & Irrigation", "Gardening"], image: "/images/products/garden-hose.jpg", short: "Flexible water hose for gardens, nurseries and everyday irrigation.", features: ["Easy handling", "Suitable for gardening and irrigation", "Custom lengths on request"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "construction-water-hose", name: "Construction Water Hose", family: "Braided Hose", applications: ["Construction", "Water Transfer"], image: "/images/products/construction-water-hose.jpg", short: "Braided water delivery hose intended for construction-site water duties.", features: ["Built for site water delivery", "Flexible handling", "Available to required length"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "welding-hose", name: "Welding Hose (Red & Blue)", family: "Braided Hose", applications: ["Welding & Gas"], image: "/images/products/welding-hose.jpg", short: "Colour-coded twin-line hose solution for welding and gas applications.", features: ["Red and blue identification", "Flexible routing around work areas", "For welding and gas use"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "super-spray-hose", name: "Super Spray Hose", family: "Braided Hose", applications: ["Spraying & Agrochemical", "Agriculture & Irrigation"], image: "/images/products/super-spray-hose.jpg", short: "Braided hose for agricultural and general spraying duties.", features: ["Designed for spray applications", "Flexible field use", "Suitable for client-specific lengths"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "car-washing-power-hose", name: "Car Washing Power Hose", family: "Braided Hose", applications: ["Automotive/Car Wash"], image: "/images/products/car-washing-power-hose.jpg", short: "Flexible hose for car washing and service-station power-wash use.", features: ["Flexible car-wash routing", "For power washing applications", "Available on request by requirement"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "five-layer-hose", name: "Five Layer Hose", family: "Braided Hose", applications: ["Agriculture & Irrigation", "Water Transfer"], image: "/images/products/five-layer-hose.jpg", short: "Multi-layer hose option for water and irrigation applications.", features: ["Five-layer construction", "Flexible handling", "Application-led selection support"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "delivery-hose-pipe", name: "Delivery Hose Pipe", family: "Delivery Hose", applications: ["Water Transfer", "Agriculture & Irrigation", "Construction"], image: "/images/products/delivery-hose-pipe.jpg", short: "PVC hose for delivery and transfer applications.", features: ["For water delivery duties", "Flexible PVC construction", "Custom packaging available on request"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "power-spray-hose", name: "Power Spray Hose", family: "Specialty Hose", applications: ["Spraying & Agrochemical", "Agriculture & Irrigation"], image: "/images/products/power-spray-hose.jpg", short: "Hose for power-spray and agricultural pesticide spraying applications.", features: ["For power spray equipment", "Flexible in field operation", "Specify required application when requesting a quote"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "rock-drill-hose", name: "Rock Drill Hose", family: "Specialty Hose", applications: ["Mining & Quarry", "Construction", "Pneumatic & Air"], image: "/images/products/rock-drill-hose.jpg", short: "Industrial hose range for rock-drilling and demanding site operations.", features: ["For drilling applications", "Designed for industrial work sites", "Discuss duty conditions with sales"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "car-washing-hose", name: "Car Washing Hose", family: "Specialty Hose", applications: ["Automotive/Car Wash"], image: "/images/products/car-washing-hose.jpg", short: "Reliable flexible water hose for automotive wash areas.", features: ["For wash-bay use", "Flexible and easy to route", "Suitable for client-specific requirements"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "thunder-hose", name: "Thunder Hose", family: "Specialty Hose", applications: ["Industrial", "Water Transfer"], image: "/images/products/thunder-hose.jpg", short: "Shivaflex specialty hose line for industrial applications.", features: ["Specialty hose line", "Application-specific selection", "Contact sales for confirmed construction and rating"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
  { slug: "garden-tubing", name: "Garden Tubing", family: "Specialty Hose", applications: ["Gardening", "Agriculture & Irrigation"], image: "/images/products/garden-tubing.jpg", short: "Flexible tubing for garden and irrigation requirements.", features: ["Flexible garden-use tubing", "For routine irrigation", "Custom length options on request"], sizes: "[TODO: confirm sizes]", workingPressure: "[TODO: confirm pressure]", burstingPressure: "[TODO: confirm pressure]" },
];

export const applications = ["Agriculture & Irrigation", "Construction", "Industrial", "Mining & Quarry", "Welding & Gas", "Spraying & Agrochemical", "Automotive/Car Wash", "Fire & Safety"];
export const productFamilies = ["Suction Hose", "Braided Hose", "Delivery Hose", "Specialty Hose"];
export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
