import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProductImage } from "@/components/ProductImage";
import { SpecTable } from "@/components/SpecTable";
import { products, getProduct } from "@/lib/products";

export function generateStaticParams() { return products.map((product) => ({ slug: product.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const product = getProduct((await params).slug); return { title: product?.name || "Product" }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const product = getProduct((await params).slug); if (!product) notFound(); return <main>
  <section className="border-b border-slate-200 bg-mist"><div className="container-site grid gap-10 py-12 lg:grid-cols-2 lg:py-16"><div><p className="eyebrow">{product.family}</p><h1 className="section-title">{product.name}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">{product.short}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`/contact?product=${encodeURIComponent(product.name)}#rfq`} className="btn-primary">Request this product</Link><a className="btn-secondary" href={`/spec-sheets/${product.slug}.pdf`} aria-label={`Download ${product.name} spec sheet`}>Download spec sheet <span className="ml-1 text-xs">[PDF]</span></a></div><p className="mt-4 text-xs text-slate-500">[TODO: add approved product spec-sheet PDF at /public/spec-sheets/{product.slug}.pdf]</p></div><div className="relative min-h-72 overflow-hidden bg-slate-200"><ProductImage src={product.image} alt={`${product.name} coil`} /></div></div></section>
  <section className="py-16"><div className="container-site grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Product overview</p><h2 className="section-title">Key features</h2><ul className="mt-6 space-y-3">{product.features.map((feature) => <li key={feature} className="flex gap-3 text-slate-700"><span className="font-bold text-brand">—</span>{feature}</li>)}</ul><h2 className="mt-10 font-display text-3xl uppercase text-ink">Applications</h2><ul className="mt-5 flex flex-wrap gap-2">{product.applications.map((application) => <li key={application} className="rounded-full bg-[#E7F1F7] px-3 py-2 text-sm font-semibold text-brand">{application}</li>)}</ul></div><div><p className="eyebrow">Specification summary</p><h2 className="section-title">Available configuration</h2><div className="mt-6"><SpecTable product={product} /></div><p className="mt-4 text-xs leading-5 text-slate-500">Final configuration, material suitability and ratings must be confirmed with Shivaflex for your operating conditions. Fields marked [TODO] await client-confirmed product data.</p><Link href={`/contact?product=${encodeURIComponent(product.name)}#rfq`} className="btn-primary mt-7">Discuss your requirement</Link></div></div></section>
</main>; }
